[workspace]
members = [
  "wayfinder",
  "wayfinder-build",
  "wayfinder-cmd",
  "wayfinder-core",
  "wayfinder-gen",
  "wayfinder-goal",
  "wayfinder-parse",
  "wayfinder-tests",
  "examples/cli",
  "examples/structured",
]
